# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: service-bindings
  labels:
    bindings.labs.vmware.com/release: devel
