# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicebindings.service.binding
  labels:
    bindings.labs.vmware.com/release: devel
    bindings.labs.vmware.com/crd-install: "true"
    duck.knative.dev/binding: "true"
spec:
  group: service.binding
  version: v1alpha2
  names:
    kind: ServiceBinding
    plural: servicebindings
    singular: servicebinding
    categories:
      - all
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Ready
      type: string
      JSONPath: ".status.conditions[?(@.type=='Ready')].status"
    - name: Reason
      type: string
      JSONPath: ".status.conditions[?(@.type=='Ready')].reason"