# Copyright 2020 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  labels:
    role: webhook
    bindings.labs.vmware.com/release: devel
  name: webhook
  namespace: service-bindings
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    role: manager
